### ISSUE TITLE
Getting 403s when using a custom theme

### ISSUE THREAD

**Issue by xolan** [appsecco/raneto-docker#1]
Changed theme in `config.default.js`.

The gulpfile task `copy_libs` only does its work for the default theme, so no files are generated for the custom theme.

**Comment by madhuakula** [comment]
Really sorry for the delay @xolan 

I have checked with the custom theme. That has to be volume mounted from local system to docker, I will update the documentation how we can do that.

Thanks

**Comment by madhuakula** [comment]
Hello @xolan 

I am sorry for the delay. Updated the documentation with fix https://github.com/appsecco/raneto-docker/commit/5cfa861514c08a942453dab9628b963701482916

You just need to update the `config.default.js` file with `/data/theme/` folder and run the below docker command mount the host system theme into container.

```bash
docker run -v `pwd`/content/:/data/content/ -v `pwd`/config/config.default.js:/opt/raneto/example/config.default.js -v `pwd`/theme/:/data/theme/ -p 3000:3000 -d appsecco/raneto
````

Thanks :smile:
