### ISSUE TITLE
Update config.default.js

### ISSUE THREAD

**Issue by 7zrty** [appsecco/raneto-docker#3]
Hey,

i was upgrading your docker image and ran into a few issues.
To be fair those origin at the raneto repo, because they assume configuration values.

First of all you need to add `searchExtraLanguages: [],` to the configuration, otherwise the search will break. Stacktrace:
```
0|raneto   | TypeError: Cannot read property 'forEach' of undefined
0|raneto   |     at getLunr (/opt/raneto/app/core/search.js:17:33)
```
Also see: https://github.com/gilbitron/Raneto/blob/master/app/core/search.js#L17

Secondly, I'd prefer if the following setting is in, too. Otherwise the home view stays blank and it alters behaviour from one image to the next.
```
// Controls behavior of home page if meta ShowOnHome is not present. If set to true
// all categories or files that do not specify ShowOnHome meta property will be shown
show_on_home_default: true,
```

Probably a disclaimer is needed in the readme, which outlines the random changes in the configuration files as potential error causes.

In general it would be good if you maintain more tags than `latest`. I tried to rollback but sadly this was no option (i think).

Keep up the good work!

**Comment by madhuakula** [comment]
Hey @7zrty 

Thank you so much for pointing the issue, I was using the config from the main repository and did not update in the current repository. 

Fixed the issue https://github.com/appsecco/raneto-docker/commit/5918dab1d3793a22b0431bfbd085b0c0e5d8651b

Thanks :+1:
