### ISSUE TITLE
Can I access the container files?

### ISSUE THREAD

**Issue by nickkostov** [appsecco/raneto-docker#7]
Hey there, 
I am trying to share the files from the container to the host I am using the kb on.
Could you please advise me on how could I get them, I wanna try and customize it as much as I can?

**Comment by madhuakula** [comment]
Hello @nickkostov 

There are multiple ways you can perform. As you can see in the documentation, we were using the volume mount option.

I think that should work fine.

Thank you

**Comment by nickkostov** [comment]
Yes, I have tried that one out. But the thing is I can no access the data stored on the container.
I figured a possible way into this using docker cp and then mapping the directories into account.

Thanks for your quick reply mate.
